# Generated by Django 3.0.5 on 2020-04-10 04:12

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
        migrations.AddField(
            model_name='blog',
            name='new_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Abc'),
            preserve_default=False,
        ),
    ]
